language: python
python:
  - "2.7"
  - "3.5"
install:
  - python setup.py install
  - pip install coveralls
script:
  - nosetests --with-coverage --cover-package=mangopi
after_success:
  - coveralls
notifications:
  webhooks: https://%WEBHOOK_ENDPOINT%/travis-ci.php
